baseURL = "/"
themesDir = "themes"
theme = "hugo-winston-theme"
title = "Sashko"
[params]
  google_analytics_id = ""
  twitter_handle = "@zerostaticio"
  showAuthorOnHomepage = true
  showAuthorOnPosts = true
  showPostsOnHomepage = true
  addFrame = true
  addDot = true